name: "Gallery Review"

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths: ["ch08/lab01/*.tf"]

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  TF_VERSION: "1.14.7"
  AWS_REGION: "ap-northeast-2"
  WORKING_DIR: "ch08/lab01"

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Format Check
        run: terraform fmt -check -recursive

      - name: Init (backend=false)
        run: terraform init -input=false -backend-config="env.dev.backend.hcl"

      - name: Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: tflint --init && tflint --recursive

      - name: Security Scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ env.WORKING_DIR }}
          soft_fail: true

  review-dev:
    needs: quality-gate # 위의 문법 검사(Quality-Gate)가 100% 통과해야만 실행됩니다.
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false -backend-config="env.dev.backend.hcl"

      # 실제 AWS를 건드리지 않고, 무엇이 추가(Add)/변경(Change)/삭제(Destroy)되는지 계획서만 뽑아냅니다.
      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -var-file="env.dev.tfvars" -no-color

      # [선택 사항] 시각적 리뷰 편의성: Plan 결과물 요약본을 개발자가 PR 창에서 바로 보게끔 댓글로 박아줍니다.
      - name: Post Plan to Pull Request
        uses: actions/github-script@v7
        if: always() # 실패하더라도 로그 확인용으로 무조건 댓글이 달리게 설정
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌
            #### Terraform Initialization ⚙️
            #### Terraform Plan 🚀
            
            <details><summary>Show Plan Result</summary>
            
            \`\`\`terraform
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            
            </details>`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

    # always()방식으로 대체
    #   - name: Fail if Plan Failed
    #     if: steps.plan.outcome == 'failure'
    #     run: exit 1